version: '3.8'

services:
  agentworkflowservice:
    build: .
    container_name: agentworkflowservice
    ports:
      - "8000:8000"  # Changed to 8000 to match the CMD in Dockerfile
      - "7900:7900"
    volumes:
      - .:/app
    shm_size: '2g'
    environment:
      - REDIS_URL=${REDIS_URL}
      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--timeout-keep-alive", "120", "--ws-ping-interval", "60", "--ws-ping-timeout", "360", "--loop", "asyncio"]

networks:
  default:
    external: true
    name: host