version: '0.1.0'

index:
  name: workflow
  prefix: workflow
  storage_type: hash

fields:
- name: event_name
  type: tag
  attrs:
    separator: ','
- name: event_description
  type: text
  attrs:
    weight: 1.0
- name: event_metadata
  type: text
  attrs:
    weight: 1.0
- name: intent_name
  type: tag
  attrs:
    separator: ','
- name: intent_description
  type: text
  attrs:
    weight: 1.0
- name: goals
  type: text
  attrs:
    weight: 1.0
- name: steps
  type: text
  attrs:
    weight: 1.0
- name: feedback
  type: text
  attrs:
    weight: 1.0
- name: models
  type: text
  attrs:
    weight: 1.0
- name: event_vector
  type: vector
  attrs:
    algorithm: flat
    data_type: float32
    dims: 768
    distance_metric: cosine
    ef_construction: 6
- name: intent_vector
  type: vector
  attrs:
    algorithm: flat
    data_type: float32
    dims: 768
    distance_metric: cosine
    ef_construction: 6
- name: metadata_vector
  type: vector
  attrs:
    algorithm: flat
    data_type: float32
    dims: 768
    distance_metric: cosine
    ef_construction: 6
- name: goals_vector
  type: vector
  attrs:
    algorithm: flat
    data_type: float32
    dims: 768
    distance_metric: cosine
    ef_construction: 6
- name: steps_vector
  type: vector
  attrs:
    algorithm: flat
    data_type: float32
    dims: 768
    distance_metric: cosine
    ef_construction: 6
- name: feedback_vector
  type: vector
  attrs:
    algorithm: flat
    data_type: float32
    dims: 768
    distance_metric: cosine
    ef_construction: 6