name: Dev Deployments

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [dev]

    strategy:
      matrix:
        python-version: [3.11.x]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Installing Dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create env file
        run: |
          touch .env
          echo PORT='8000' >> .env
          echo SUPABASE_ANON_KEY='${{ secrets.SUPABASE_ANON_KEY_DEV }}' >> .env
          echo SUPABASE_URL='${{ secrets.SUPABASE_URL_DEV }}' >> .env
          echo KAFKA_BROKER_URL='${{ secrets.KAFKA_BROKER_URL_DEV }}' >> .env
          echo REDIS_URL='${{ secrets.REDIS_URL_DEV }}' >> .env
          echo NODE_ENV='development' >> .env
          cat .env

      - name: Start FastAPI Application
        run: |
          source venv/bin/activate
          nohup venv/bin/python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 &

    environment:
      name: Development
